### ISSUE TITLE
Compile GAuthPayload_pb2.py locally

### ISSUE THREAD

**Issue by mb300sd** [wmdebrito/googleOTP-to-andOTP#1]
I could not get this to work with the provided GAuthPayload_pb2.py, but after running 

```
rm GAuthPayload_pb2.py
protoc --python_out=. GAuthPayload.proto
```

It worked.

Original error:

```
Traceback (most recent call last):
  File "toAndOTP.py", line 3, in <module>
    from GAuthPayload_pb2 import GAuthPayload
  File "/root/googleOTP-to-andOTP/GAuthPayload_pb2.py", line 21, in <module>
    serialized_pb=b'\n\x12GAuthPayload.proto\"\xf0\x02\n\x0cGAuthPayload\x12&\n\x07payload\x18\x01 \x03(\x0b\x32\x15.GAuthPayload.Payload\x12\x0f\n\x07version\x18\x02 \x01(\x05\x12\x12\n\nbatch_size\x18\x03 \x01(\x05\x12\x13\n\x0b\x62\x61tch_index\x18\x04 \x01(\x05\x12\x10\n\x08\x62\x61tch_id\x18\x05 \x01(\x05\x1a\xa3\x01\n\x07Payload\x12\x0e\n\x06secret\x18\x01 \x01(\x0c\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06issuer\x18\x03 \x01(\t\x12$\n\talgorithm\x18\x04 \x01(\x0e\x32\x11.GAuthPayload.Alg\x12\x0e\n\x06\x64igits\x18\x05 \x01(\x05\x12#\n\x04type\x18\x06 \x01(\x0e\x32\x15.GAuthPayload.OtpType\x12\x0f\n\x07\x63ounter\x18\x07 \x01(\x03\"\x1a\n\x03\x41lg\x12\t\n\x05\x45RROR\x10\x00\x12\x08\n\x04SHA1\x10\x01\"*\n\x07OtpType\x12\x0b\n\x07INVALID\x10\x00\x12\x08\n\x04HOTP\x10\x01\x12\x08\n\x04TOTP\x10\x02\x62\x06proto3'
TypeError: __new__() got an unexpected keyword argument 'serialized_options'
```

Probably a good idea to add it to the instructions or do it automatically.

**Comment by wmdebrito** [comment]
Instructions were updated. thank you for the feedback.
